In [34]:
# resumpleメソッドの勉強
import pandas_datareader.data as pdr

start = "1949/5/6"
end = "2016/9/30"

# very useful sight
# http://www.webpages.uidaho.edu/~stevel/504/Pandas%20DataFrame%20Notes.pdf

# pandas_datareaderを使って、yahooからNIKKEI225のデータを読み込み
n225 = pdr.DataReader("^N225", 'yahoo', start, end)

# 2016年の高値と低値の値を表示
print('\n--- 1. n225From2016.ix["2016",["High","Low"]].head(30) <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].head(30))

# 2016年の　月初めの　高値と低値の値を表示
print('\n--- 2-1. n225From2016.resample(\'MS\').first() <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].resample('MS').first())

# 2016年の　月最終日　高値と低値の値を表示
print('\n--- 2-2. n225From2016.resample(\'M\').last() <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].resample('M').last())

# 2016年1月の　高値と低値の平均
print('\n--- 3-1. n225.ix["2016/1",["High","Low"]].mean() <Series> ---')
print(n225.ix["2016/1",["High","Low"]].mean())

# 2016年2月の　高値と低値の平均
print('\n--- 3-2. n225.ix["2016/2",["High","Low"]].mean() <Series> ---')
print(n225.ix["2016/2",["High","Low"]].mean())

# 2016年の月ごとの　高値と低値の平均　日付は月初めに寄せて表示
print('\n--- 3-3. n225.ix["2016",["High","Low"]].resample(\'MS\').mean().head(5) <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].resample('MS').mean().head(5))

# 2016年の月ごとの　高値と低値の平均　日付は月終わりに寄せて表示
print('\n--- 3-4. n225.ix["2016",["High","Low"]].resample(\'M\').mean().head(5) <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].resample('M').mean().head(5))

# 2016年の月ごとの　高値と低値の平均　日付は月終わりに寄せて表示
print('\n--- 3-5. n225.ix["2016",["High","Low"]].resample(\'M\').mean().tail(2) <DataFrame> ---')
print(n225.ix["2016",["High","Low"]].resample('M').mean().tail(2))

--- 1. n225From2016.ix["2016",["High","Low"]].head(30) <DataFrame> ---
                    High           Low
Date
2016-01-04  18951.119141  18394.429688
2016-01-05  18547.380859  18327.519531
2016-01-06  18469.380859  18064.300781
2016-01-07  18172.039062  17767.339844
2016-01-08  17975.310547  17509.640625
2016-01-12  17546.570312  17184.779297
2016-01-13  17717.750000  17414.550781
2016-01-14  17393.830078  16944.410156
2016-01-15  17597.869141  17057.599609
2016-01-18  17037.259766  16665.050781
2016-01-19  17088.310547  16812.650391
2016-01-20  17031.320312  16387.609375
2016-01-21  16734.580078  16017.259766
2016-01-22  16993.960938  16332.450195
2016-01-25  17208.240234  16922.210938
2016-01-26  16839.519531  16652.259766
2016-01-27  17242.269531  16947.949219
2016-01-28  17235.439453  16942.130859
2016-01-29  17638.929688  16767.089844
2016-02-01  17905.369141  17666.480469
2016-02-02  17864.699219  17684.660156
2016-02-03  17515.679688  17080.570312
2016-02-04  17209.560547  16941.880859
2016-02-05  16893.119141  16627.800781
2016-02-08  17099.009766  16552.300781
2016-02-09  16668.699219  16025.940430
2016-02-10  16163.030273  15429.990234
2016-02-12  15437.219727  14865.769531
2016-02-15  16155.099609  15243.879883
2016-02-16  16341.559570  15809.580078

--- 2-1. n225From2016.resample('MS').first() <DataFrame> ---
                    High           Low
Date
2016-01-01  18951.119141  18394.429688
2016-02-01  17905.369141  17666.480469
2016-03-01  16099.419922  15857.370117
2016-04-01  16719.560547  16113.009766
2016-05-01  16357.099609  15975.469727
2016-06-01  17145.949219  16908.919922
2016-07-01  15765.000000  15635.570312
2016-08-01  16677.490234  16319.150391
2016-09-01  16941.179688  16864.560547

--- 2-2. n225From2016.resample('M').last() <DataFrame> ---
                    High           Low
Date
2016-01-31  17638.929688  16767.089844
2016-02-29  16464.750000  16026.759766
2016-03-31  17033.650391  16758.669922
2016-04-30  17572.269531  16652.740234
2016-05-31  17251.359375  16988.640625
2016-06-30  15781.690430  15575.919922
2016-07-31  16679.189453  16174.349609
2016-08-31  16917.859375  16836.960938
2016-09-30  16497.550781  16407.779297

--- 3-1. n225.ix["2016/1",["High","Low"]].mean() <Series> ---
High    17548.477899
Low     17111.117445
dtype: float64

--- 3-2. n225.ix["2016/2",["High","Low"]].mean() <Series> ---
High    16577.776318
Low     16161.000635
dtype: float64

--- 3-3. n225.ix["2016",["High","Low"]].resample('MS').mean().head(5) <DataFrame> ---
                    High           Low
Date
2016-01-01  17548.477899  17111.117445
2016-02-01  16577.776318  16161.000635
2016-03-01  17002.123136  16759.662065
2016-04-01  16712.441943  16387.763623
2016-05-01  16724.345703  16488.068771

--- 3-4. n225.ix["2016",["High","Low"]].resample('M').mean().head(5) <DataFrame> ---
                    High           Low
Date
2016-01-31  17548.477899  17111.117445
2016-02-29  16577.776318  16161.000635
2016-03-31  17002.123136  16759.662065
2016-04-30  16712.441943  16387.763623
2016-05-31  16724.345703  16488.068771

--- 3-5. n225.ix["2016",["High","Low"]].resample('M').mean().tail(2) <DataFrame> ---
                    High           Low
Date
2016-08-31  16669.787598  16498.300426
2016-09-30  16796.954297  16635.677002