In [45]:
# resumpleメソッドの勉強
import pandas_datareader.data as pdr

start = "1949/5/6"
end = "2016/9/30"

# pandas_datareaderを使って、yahooからNIKKEI225のデータを読み込み 2016年以降にスライス <DataFrame>
price = pdr.DataReader("^N225", 'yahoo', start, end)
priceFrom2016 = price.ix["2016/1/1":]
print('\n--- 1. priceFrom2016 <DataFrame> ---')
print(priceFrom2016.resample('M').head(12))

# 2016年以降のNIKKEI225のデータ 1月の最初のレコード(2016/1/4)を取得 <Series>
print('\n--- 2-1. priceFrom2016.ix["2016/1/4"] <Sceries> ---')
print(priceFrom2016.ix["2016/1/4"])

# 2016年以降のNIKKEI225のデータ 1月の最初のレコード(2016/1/4)を取得 <Series>
print('\n--- 2-2. priceFrom2016.ix["2016/2/1"] <Sceries> ---')
print(priceFrom2016.ix["2016/2/1"])

# 2016年以降のNIKKEI225のデータ resampleを使って月ごとにし、各月の最初のレコードを取得 <DataFrame>
# データが無い場合でも、日付は各月の最初の日(１日)が表示される。
print('\n--- 2-3. priceFrom2016.resample(\'M\').first() <DataFrame> ---')
print(priceFrom2016.resample('M').first())


# 2016年以降のNIKKEI225のデータ resampleを使って月ごとにし、各月の最初のレコードを取得 <DataFrame>
# データが無い場合でも、日付は各月の最初の日(１日)が表示される。
print('\n--- 2-3. priceFrom2016.resample(\'M\').first().tail() <DataFrame> ---')
print(priceFrom2016.resample('M').first().tail())

# 2016年以降のNIKKEI225のデータ 1月の最後のレコード(2016/1/29)を取得 <Series>
print('\n--- 3-1. priceFrom2016.ix["2016/1/29"] <Sceries> ---')
print(priceFrom2016.ix["2016/1/29"])

# 2016年以降のNIKKEI225のデータ 1月の最後のレコード(2016/1/29)を取得 <Series>
print('\n--- 3-2. priceFrom2016.ix["2016/2/29"] <Sceries> ---')
print(priceFrom2016.ix["2016/2/29"])

# 2016年以降のNIKKEI225のデータ resampleを使って月ごとにし、各月の最後のレコードを取得 <DataFrame>
# 日付は各月の最終日(30日とか、31日とか)が表示される。
print('\n--- 3-3. priceFrom2016.resample(\'M\').last() <DataFrame> ---')
print(priceFrom2016.resample('M').last())

--- 1. priceFrom2016 <DataFrame> ---
                    Open          High           Low         Close  \
Date
2016-01-31  17361.234632  17548.477899  17111.117445  17302.297389
2016-02-29  16373.993750  16577.776318  16161.000635  16346.961035
2016-03-31  16884.493075  17002.123136  16759.662065  16897.340465
2016-04-30  16561.778174  16712.441943  16387.763623  16543.467432
2016-05-31  16627.957854  16724.345703  16488.068771  16612.673160
2016-06-30  16137.717285  16252.517312  15934.485041  16068.810813
2016-07-31  16138.074512  16275.584131  16046.254492  16168.319629
2016-08-31  16578.432928  16669.787598  16498.300426  16586.070401
2016-09-30  16715.323926  16796.954297  16635.677002  16737.041406

                   Volume     Adj Close
Date
2016-01-31  158021.052632  17302.297389
2016-02-29  164180.000000  16346.961035
2016-03-31  100840.909091  16897.340465
2016-04-30  142740.000000  16543.467432
2016-05-31  103547.368421  16612.673160
2016-06-30  120054.545455  16068.810813
2016-07-31  941220.000000  16168.319629
2016-08-31   80890.909091  16586.070401
2016-09-30   92970.000000  16737.041406

--- 2-1. priceFrom2016.ix["2016/1/4"] <Sceries> ---
Open          18818.580078
High          18951.119141
Low           18394.429688
Close         18450.980469
Volume       136000.000000
Adj Close     18450.980469
Name: 2016-01-04 00:00:00, dtype: float64

--- 2-2. priceFrom2016.ix["2016/2/1"] <Sceries> ---
Open         17699.599609
High         17905.369141
Low          17666.480469
Close        17865.230469
Volume           0.000000
Adj Close    17865.230469
Name: 2016-02-01 00:00:00, dtype: float64

--- 2-3. priceFrom2016.resample('M').first() <DataFrame> ---
                    Open          High           Low         Close  Volume  \
Date
2016-01-31  18818.580078  18951.119141  18394.429688  18450.980469  136000
2016-02-29  17699.599609  17905.369141  17666.480469  17865.230469       0
2016-03-31  16013.000000  16099.419922  15857.370117  16085.509766  147700
2016-04-30  16719.560547  16719.560547  16113.009766  16164.160156  173000
2016-05-31  16357.099609  16357.099609  15975.469727  16147.379883  174500
2016-06-30  17097.220703  17145.949219  16908.919922  16955.730469  129700
2016-07-31  15698.019531  15765.000000  15635.570312  15682.480469  116300
2016-08-31  16415.310547  16677.490234  16319.150391  16635.769531  168900
2016-09-30  16885.160156  16941.179688  16864.560547  16926.839844  127600

               Adj Close
Date
2016-01-31  18450.980469
2016-02-29  17865.230469
2016-03-31  16085.509766
2016-04-30  16164.160156
2016-05-31  16147.379883
2016-06-30  16955.730469
2016-07-31  15682.480469
2016-08-31  16635.769531
2016-09-30  16926.839844

--- 2-3. priceFrom2016.resample('M').first().tail() <DataFrame> ---
                    Open          High           Low         Close  Volume  \
Date
2016-05-31  16357.099609  16357.099609  15975.469727  16147.379883  174500
2016-06-30  17097.220703  17145.949219  16908.919922  16955.730469  129700
2016-07-31  15698.019531  15765.000000  15635.570312  15682.480469  116300
2016-08-31  16415.310547  16677.490234  16319.150391  16635.769531  168900
2016-09-30  16885.160156  16941.179688  16864.560547  16926.839844  127600

               Adj Close
Date
2016-05-31  16147.379883
2016-06-30  16955.730469
2016-07-31  15682.480469
2016-08-31  16635.769531
2016-09-30  16926.839844

--- 3-1. priceFrom2016.ix["2016/1/29"] <Sceries> ---
Open          17155.060547
High          17638.929688
Low           16767.089844
Close         17518.300781
Volume       285600.000000
Adj Close     17518.300781
Name: 2016-01-29 00:00:00, dtype: float64

--- 3-2. priceFrom2016.ix["2016/2/29"] <Sceries> ---
Open          16313.309570
High          16464.750000
Low           16026.759766
Close         16026.759766
Volume       159400.000000
Adj Close     16026.759766
Name: 2016-02-29 00:00:00, dtype: float64

--- 3-3. priceFrom2016.resample('M').last() <DataFrame> ---
                    Open          High           Low         Close  Volume  \
Date
2016-01-31  17155.060547  17638.929688  16767.089844  17518.300781  285600
2016-02-29  16313.309570  16464.750000  16026.759766  16026.759766  159400
2016-03-31  16997.140625  17033.650391  16758.669922  16758.669922  152800
2016-04-30  17438.990234  17572.269531  16652.740234  16666.050781  226100
2016-05-31  17029.460938  17251.359375  16988.640625  17234.980469  152000
2016-06-30  15752.709961  15781.690430  15575.919922  15575.919922  146200
2016-07-31  16359.679688  16679.189453  16174.349609  16569.269531  227600
2016-08-31  16857.830078  16917.859375  16836.960938  16887.400391  145800
2016-09-30  16474.449219  16497.550781  16407.779297  16449.839844  120700

               Adj Close
Date
2016-01-31  17518.300781
2016-02-29  16026.759766
2016-03-31  16758.669922
2016-04-30  16666.050781
2016-05-31  17234.980469
2016-06-30  15575.919922
2016-07-31  16569.269531
2016-08-31  16887.400391
2016-09-30  16449.839844

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: FutureWarning: .resample() is now a deferred operation
use .resample(...).mean() instead of .resample(...)